apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.slamApp.name }}-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
