apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.slamApp.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  hosts:
  - {{ .Values.externalApiRoot }}
  gateways:
  - istio-ingress/external-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.slamApp.path }}/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.slamApp.name }}
        port:
          number: 80
